name: Java CI

on: [push]

jobs:
    
  ontdoc:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc      
    with: 
          rdffilepath: signlist.ttl
          version: v017dev
          docpath: docs/
          prefixns: https://situx.github.io/cuneiformontology/
          prefixnsshort: cuneisignlist
          indexpages: true
          metadatatable: true
          createcollections: false
          iiif: true
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: rdf

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initial checkout
      uses: actions/checkout@v3
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: .
